[workflows][csharp] Adding diff output to formatting check.

diff --git a/.github/workflows/format-check-csharp.yml b/.github/workflows/format-check-csharp.yml
--- a/.github/workflows/format-check-csharp.yml
+++ b/.github/workflows/format-check-csharp.yml
@@ -20,5 +20,11 @@ jobs:
 
     - name: Check for changes
       run: |
+        git add .
+        git reset .
         git ls-files -m
-        if [[ `git ls-files -m` ]]; then echo "Detected C# formatting errors!" & exit 1; fi
+        if [[ `git ls-files -m` ]]; then
+          git diff
+          git diff > format-diff.txt
+          echo "Detected C# formatting errors!" & exit 1;
+        fi
